// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }

  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5O-g-eR4AGNnvSNB8jCtIReYwNydsq08',
    appId: '1:1002804230337:android:53d1719906955b20d93c40',
    messagingSenderId: '1002804230337',
    projectId: 'gemstore-5678',
    storageBucket: 'gemstore-5678.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJFmsVOj_n16PTJ4BkEk1ehCiBauvbCGI',
    appId: '1:1002804230337:ios:9e206e99572f1922d93c40',
    messagingSenderId: '1002804230337',
    projectId: 'gemstore-5678',
    storageBucket: 'gemstore-5678.firebasestorage.app',
    iosClientId: '1002804230337-nhnfn0pd4gbmj6hlge1l8qtbke0dvqpn.apps.googleusercontent.com',
    iosBundleId: 'com.example.gemStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBK1ayvWWWM7B29O0wX-B5N2YSff7AHNow',
    appId: '1:1002804230337:web:188c6bf8c09c2cd6d93c40',
    messagingSenderId: '1002804230337',
    projectId: 'gemstore-5678',
    authDomain: 'gemstore-5678.firebaseapp.com',
    storageBucket: 'gemstore-5678.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJFmsVOj_n16PTJ4BkEk1ehCiBauvbCGI',
    appId: '1:1002804230337:ios:9e206e99572f1922d93c40',
    messagingSenderId: '1002804230337',
    projectId: 'gemstore-5678',
    storageBucket: 'gemstore-5678.firebasestorage.app',
    iosClientId: '1002804230337-nhnfn0pd4gbmj6hlge1l8qtbke0dvqpn.apps.googleusercontent.com',
    iosBundleId: 'com.example.gemStore',
  );

}